<?php 
include("database/mydb.php"); 
// $email = 'gjhwatters@gmail.com'; 
$sql = $con->query("SELECT subscriberID FROM customer_details  limit 1".mysqli_error($con)); 
if ($sql->num_rows != 0) {
    // code...
    while ($rows = $sql->fetch_assoc()) {
        // code...
        $subscriberID = $rows['subscriberID'];
    }
}

?>

<?php 
$token = $_GET['access_token'];
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/billing/subscriptions/'.rawurlencode($subscriberID).'/cancel');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer '.rawurlencode($token);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$err = curl_error($ch);
curl_close($ch); 
if ($err) {
  // code...
  echo 'Error:'.$err; 
}
else {
    $sql="UPDATE customer_details SET status = 'CANCELLED', subscriberID = '', PlanID = '', start_time = '', status_update_time = '', fullname = '', payment_email_address = '' WHERE session_email = '$email'".mysqli_error($con); 
    $query_result = $con->query($sql);
    if ($query_result) {
        // code...
        header("Location: cancelSuccess.php?subscriptions=Cancelled");
        exit();
    }
    else{
        echo "Error".mysqli_error($con);
    }

}

?>